version: '3.8'

services:
  app:
    image: node:18
    container_name: my-node-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: "npm start"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
